### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by morinted** [abarnert/pykeycode#4]
Hi,

I'd like to use pykeycode in Plover, a free stenography program. I need a way to detect the user's layout in order to properly emulate it. Could you clarify the license on the code?

Much obliged,
Ted

**Comment by abarnert** [comment]
Sorry, it's supposed to be... Whichever permissive license (MIT) is the first choice on GitHub. I'll fix it when I get to my computer. (I just need to double-check that there isn't a table generated by parsing non-permissively-licensed source code or anything first.)

**Comment by abarnert** [comment]
Added the MIT license file.
